### ISSUE TITLE
Error while restoring

### ISSUE THREAD

**Issue by bally1986** [Devjam81/libimobile2019#3]
I'm getting the error below when restoring an IOS13 IPSW. The phone stays in recovery mode. Any suggestions?

ERROR: Unable to send iBEC component: Unable to find device
ERROR: Unable to send iBEC to device.
ERROR: Unable to send iBEC

**Comment by icyred64** [comment]
I can Confirm. I have the exact same issue.
Iphone XS Max, version 12.3.1. Downloaded IOS13 XS Max, Libimoible2019-master. Entered the command in Command prompt and a giant list of codes ect went thru screen but after a minute this is how it ends.

Received SHSH blobs
DEBUG: tss_response_get_path_by_entry: No entry 'iBEC' in TSS response
NOTE: No path for component iBEC in TSS, will fetch from build_identity
Extracting iBEC.d331p.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Tag found
Sending iBEC (1104089 bytes)...
ERROR: Unable to send iBEC component: Unable to find device
ERROR: Unable to send iBEC to device.
ERROR: Unable to send iBEC

**Comment by bally1986** [comment]
Finaly got it running.
Uninstalled Itunes
Reinstalled Itunes (Not the windows store version)
Had to restore my iphone from 12.4 beta to 12.3.1
Restored to IOS13
